### ISSUE TITLE
Updating to version 4.7.2

### ISSUE THREAD

**Issue by ghost** [sebt3/hubzilla#4]
Hey @sebt3,

It's been a while, mate.

I've tried, unsuccessfully to update the image to version 4.7.2 (and alpine to 3.12, php to 7.4, etc)

is this something you have considered giving a go?

Hubzilla 4.7.2, has been released, and fixes everything in the patch file (there are more fixes that I've slapped together into a patch. So I can provide that).

Also, the codebase has moved (not entirely, but it will) to codeberg.org.

The image that I have made builds, but it returns that annoying php child error, and doesn't serve when attached to nginx.
If you wanted to have a look at what I've done, I'm more than happy to share

**Comment by sebt3** [comment]
Thanks for the head-up :)
I had 90% of the work already done, but I probably got interrupted, since I didnt finished. Now it is done. Check latest commit.

I havent tested it yet, but the image build with all your requierements. Keep me posted, I'll build all the images version (x86_64, armhf and arm64) and publish once you confirm the image works as expected ;)

**Comment by sebt3** [comment]
The x86_64 image i've built works as expected (on my test environnement), i'm currently building the arm and arm64 images. I'll probably push the manifest once I'm back from work

**Comment by sebt3** [comment]
The manifest sebt3/hubzilla:4.7.2 is available on hub.docker. Closing :)

**Comment by ghost** [comment]
awesome, man. Love your work
